### ISSUE TITLE
Gstreamer Example

### ISSUE THREAD

**Issue by acschristoph** [jhenstridge/asyncio-glib#12]
Hi 

Do you have a gstreamer Example?
I want to use asyncio websocketes to emit Data on a gatreamer callback. Is that possible with your project? Big thanks

BR

**Comment by alex-eri** [comment]
gstreamer runs on its own threads, so glib integration not realy needed. Just use asyncio.Queue put_nowait and task for read this queue

**Comment by acschristoph** [comment]
ok thanks
